development:
  adapter: postgresql
  encoding: unicode
  database: drako_development
  pool: 5
  username: snake
  password: vyvsam
  port: 8080

test:
  adapter: postgresql
  encoding: unicode
  database: drako_test
  pool: 5
  username: snake
  password: vyvsam
  port: 8080

production:
  adapter: postgresql
  encoding: unicode
  database: drako_production
  pool: 5
  username: snake
  password: vyvsam
  port: 8080
